# Generated by Django 5.2.5 on 2025-08-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_kompyuter_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="kompyuter",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="computer_images/"
            ),
        ),
    ]
