# Generated by Django 5.2.5 on 2025-08-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_kompyuter_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kompyuter",
            name="image",
            field=models.ImageField(
                blank=True,
                default="computer_images/default.jpg",
                null=True,
                upload_to="computer_images/",
            ),
        ),
    ]
